make ip_from can select ip_source, ip_interface
ericpaulbishop/gargoyle pull request #917
Opened 2021-04-01 23:24 UTC by livepu

(cherry picked from commit 8efce52c52c406b10a6e589966d3fc04b173d690)

# Conflicts:
#	package/plugin-gargoyle-ddns/files/www/templates/ddns_service_template

2021-04-01 23:39 UTC, lantis1008 requested changes
Thanks for this. Please see individual feedback items. 
Also @ericpaulbishop do you have any objections? Are you still working on ddns? Do not want to conflict your changes.

2021-04-01 23:39 UTC, lantis1008 commented on package/plugin-gargoyle-ddns/files/www/js/ddns.js
> +	var ip_from=document.getElementById("ip_from").value;//select or  input? input is easy
Please cleanup comments

2021-04-01 23:39 UTC, lantis1008 commented on package/plugin-gargoyle-ddns/files/www/js/ddns.js
> +	if(ip_from!="internet"){
Please use standard Gargoyle coding style (braces get their own line)

2021-04-01 23:39 UTC, lantis1008 commented on package/plugin-gargoyle-ddns/files/www/js/ddns.js
> +	if(ip_from){
Please replace this section with setSelectedValue or srtSelectedText (whichever is most appropriate)

2021-04-01 23:39 UTC, lantis1008 commented on package/plugin-gargoyle-ddns/files/www/templates/ddns_service_template
> +					<label class="col-xs-5" for="ip_from" id="ip_from_label">ip_from:</label>
Missing i18n translations

2021-04-01 23:39 UTC, lantis1008 commented on package/plugin-gargoyle-ddns/files/www/templates/ddns_service_template
> +						<option value="internet">internet</option>
Please fix indentation in this area

2021-04-02 05:02 UTC, livepu commented
Sorry, I didn't understand this standard before. Or I need you to deal with it. I don't really know how to use GitHub.

It was a test at the beginning, and it was stable after a period of time. Recently, someone mentioned that DDNS is unstable, so this code is issued.

2021-04-02 07:56 UTC, lantis1008 commented
I will fix your code in this instance, once Eric has had an opportunity to respond. 
For what it's worth, this doesn't fix ddns. For some people this option may be more appropriate. For most users, it is not needed. Issues reported for earlier versions of 1.12 around the aruljohn site have been fixed. If people won't use the latest versions, how is your fix going to help them either lol?
However, you have gone to the effort of exposing the option, so I will include it. I appreciate your efforts, thank you.

2021-04-11 06:07 UTC, closed without merging