Update WNDR3500 v5 profile image regexp to match OpenWrt 19.07 naming
ericpaulbishop/gargoyle pull request #937
Opened 2021-12-28 13:50 UTC by aimacintyre

See image names for 19.07.8 at
https://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt7621/

2021-12-28 14:12 UTC, aimacintyre commented
Sorry - typo in the commit header: "WNDR3500" should be "WNDR3700"  - how best to fix?  (I'm still trying to find my way with git).

2021-12-28 21:43 UTC, lantis1008 requested changes
You can fix the pull request title from GitHub. 
The commit title must be amended. The following stackoverflow answer gives quite a good summary of your options, including instructions for force pushing your changes. 
Take note of the force push warning. In this case as I have not merged your change, there is no risk of creating mismatching histories. 
https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

2021-12-28 23:03 UTC, aimacintyre commented
Thanks for that, hopefully I've made the change correctly.

2021-12-29 02:28 UTC, lantis1008 commented
That’s great. I will merge this later today. 
Minor nitpick and not crucial, but you could also edit the title of this pull request to match as well. It carries no consequences moving forward and if you haven’t done it when I’m ready to merge it won’t stop anything. 
Thanks again for your contribution!

2021-12-29 03:15 UTC, aimacintyre commented
Title now fixed.

2021-12-29 09:25 UTC, merged